specVersion: 1.0.0
name: juno-subql-starter
version: 0.0.1
runner:
  node:
    name: "@subql/node-cosmos"
    version: ">=0.1.0"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  This project can be use as a starting point for developing your Cosmos (Juno) based SubQuery project
repository: https://github.com/subquery/juno-subql-starter
schema:
  file: ./schema.graphql

network:
  chainId: juno-1
  endpoint: https://rpc.juno-1.api.onfinality.io
  #chainId: testing #for local node
  #endpoint: http://node:26657/
  # Using a dictionary can massively improve indexing speed
  dictionary: https://api.subquery.network/sq/subquery/cosmos-juno-dictionary

dataSources:
  - kind: cosmos/Runtime
    startBlock: 4175250 # first block on juno-1 - 4136532 # 4175250
    #chainTypes: # This is a beta feature that allows support for any Cosmos chain by importing the correct protobuf messages
    #  cosmos.slashing.v1beta1:
    #    file: "./proto/cosmos/slashing/v1beta1/tx.proto"
    #    messages:
    #     - "MsgUnjail"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleUpdateSettings # Methods called by the owner
          kind: cosmos/MessageHandler
          filter:
            type: "/cosmwasm.wasm.v1.MsgExecuteContract"
            contractCall: "update_settings"
            contract: "juno13tk76epuctgtg4g9y3s0lyjvjq26x59dnqrjw86c975a44mcpm6qnlnkvm"
        - handler: handleMoveBalances
          kind: cosmos/MessageHandler
          filter:
            type: "/cosmwasm.wasm.v1.MsgExecuteContract"
            contractCall: "move_balances"
            contract: "juno13tk76epuctgtg4g9y3s0lyjvjq26x59dnqrjw86c975a44mcpm6qnlnkvm"
        - handler: handleCreateTask # Methods for tasks 
          kind: cosmos/MessageHandler
          filter:
            type: "/cosmwasm.wasm.v1.MsgExecuteContract"
            contractCall: "create_task"
            contract: "juno13tk76epuctgtg4g9y3s0lyjvjq26x59dnqrjw86c975a44mcpm6qnlnkvm"
        - handler: handleRemoveTask
          kind: cosmos/MessageHandler
          filter:
            type: "/cosmwasm.wasm.v1.MsgExecuteContract"
            contractCall: "remove_task"
            contract: "juno13tk76epuctgtg4g9y3s0lyjvjq26x59dnqrjw86c975a44mcpm6qnlnkvm"
        - handler: handleRefillTaskBalance
          kind: cosmos/MessageHandler
          filter:
            type: "/cosmwasm.wasm.v1.MsgExecuteContract"
            contractCall: "refill_task_balance"
            contract: "juno13tk76epuctgtg4g9y3s0lyjvjq26x59dnqrjw86c975a44mcpm6qnlnkvm"
        - handler: handleRegisterAgent # Agent methods
          kind: cosmos/MessageHandler
          filter:
            type: "/cosmwasm.wasm.v1.MsgExecuteContract"
            contractCall: "register_agent"
            contract: "juno13tk76epuctgtg4g9y3s0lyjvjq26x59dnqrjw86c975a44mcpm6qnlnkvm"
        - handler: handleUpdateAgent
          kind: cosmos/MessageHandler
          filter:
            type: "/cosmwasm.wasm.v1.MsgExecuteContract"
            contractCall: "update_agent"
            contract: "juno13tk76epuctgtg4g9y3s0lyjvjq26x59dnqrjw86c975a44mcpm6qnlnkvm"
        - handler: handleUnregisterAgent
          kind: cosmos/MessageHandler
          filter:
            type: "/cosmwasm.wasm.v1.MsgExecuteContract"
            contractCall: "unregister_agent"
            contract: "juno13tk76epuctgtg4g9y3s0lyjvjq26x59dnqrjw86c975a44mcpm6qnlnkvm"
        - handler: handleWithdrawReward
          kind: cosmos/MessageHandler
          filter:
            type: "/cosmwasm.wasm.v1.MsgExecuteContract"
            contractCall: "withdraw_agent_balance"
            contract: "juno13tk76epuctgtg4g9y3s0lyjvjq26x59dnqrjw86c975a44mcpm6qnlnkvm"
        - handler: handleCheckInAgent
          kind: cosmos/MessageHandler
          filter:
            type: "/cosmwasm.wasm.v1.MsgExecuteContract"
            contractCall: "check_in_agent"
            contract: "juno13tk76epuctgtg4g9y3s0lyjvjq26x59dnqrjw86c975a44mcpm6qnlnkvm"
        - handler: handleProxyCall
          kind: cosmos/MessageHandler
          filter:
            type: "/cosmwasm.wasm.v1.MsgExecuteContract"
            contractCall: "proxy_call"
            contract: "juno13tk76epuctgtg4g9y3s0lyjvjq26x59dnqrjw86c975a44mcpm6qnlnkvm"

